version: "3"
services:
    php5:
        container_name: ws-php5
        hostname: php5
        restart: "no"
        build:
            dockerfile: Dockerfile
            context: php5
            args:
                LANGUAGE: pt_BR.UTF-8
                TIMEZONE: America/Sao_Paulo
        depends_on:
            - db
            - redis
        environment:
            - PHP_IDE_CONFIG=serverName=XdebugServer
        volumes:
            - "./default/.bashrc:/root/.bashrc"
            - "./php5/conf.d/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini"
            - "./php5/logging.conf:/usr/local/etc/php-fpm.d/logging.conf"
            - "./logs:/var/log"
            - "../:/var/www/html"
            - "~/.ssh:/~/.ssh"
        expose:
            - "9000"
        ports:
            - '9000:9000'
        stdin_open: true
        tty: true
        networks:
            ws-network:
                ipv4_address: 172.8.0.10
    php7:
        container_name: ws-php7
        hostname: php7
        restart: "no"
        build:
            dockerfile: Dockerfile
            context: php7
            args:
                LANGUAGE: pt_BR.UTF-8
                TIMEZONE: America/Sao_Paulo
        depends_on:
            - db
            - redis
        environment:
            - SYMFONY_ENV=dev
            - PHP_IDE_CONFIG=serverName=XdebugServer
        volumes:
            - "./default/.bashrc:/root/.bashrc"
            - "./php7/conf.d/99-custom.ini:/usr/local/etc/php/conf.d/99-custom.ini"
            - "./logs:/var/log"
            - "../:/var/www/html"
            - "~/.ssh:/~/.ssh"
        expose:
            - '9000'
        ports:
            - '9007:9000'
        stdin_open: true
        tty: true
        networks:
            ws-network:
                ipv4_address: 172.8.0.11
    db:
        image: "mysql:5.6"
        container_name: ws-mysql
        hostname: mysql
        restart: "no"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: database
        volumes:
            - "./default/.bashrc:/root/.bashrc"
            - "./mysql/conf.d/custom.cnf:/etc/mysql/conf.d/custom.cnf"
            - "./mysql/data:/var/lib/mysql:rw"
        ports:
            - "3303:3306"
        networks:
            ws-network:
                ipv4_address: 172.8.0.13
    redis:
        image: "redis:latest"
        container_name: cacheserver
        restart: "no"
        ports:
            - "6379:6379"
        networks:
            ws-network:
                ipv4_address: 172.8.0.14
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ws-phpmyadmin
        restart: "no"
        depends_on:
            - db
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOSTS=db
            - PMA_USER=root
            - PMA_PASSWORD=root
        ports:
            - "8080:80"
        networks:
            ws-network:
                ipv4_address: 172.8.0.15
        volumes:
            - "./default/.bashrc:/root/.bashrc"
            - "./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php"
    nginx:
        image: 'nginx:alpine'
        container_name: ws-nginx
        volumes:
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
            - "./logs:/var/log/nginx"
            - "../:/var/www/html"
        ports:
            - '80:80'
        depends_on:
            - php5
        links:
            - php5
            - php7
        networks:
            ws-network:
                ipv4_address: 172.8.0.16
networks:
    ws-network:
        name: "ws-network"
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.8.0.0/24
